plugins {
    id 'net.minecraftforge.gradle' version '5.1.+'
}

group = 'com.velax'
version = '1.0'

java {
    archivesBaseName = 'VelaxParasiteWheel'
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                parasitewheel {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/main/resources' }

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
}

jar {
    manifest {
        attributes([
            "Specification-Title"     : "VelaxParasiteWheel",
            "Specification-Vendor"    : "Velax31",
            "Specification-Version"   : "1",
            "Implementation-Title"    : project.name,
            "Implementation-Version"  : project.version,
            "Implementation-Vendor"   : "Velax31",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
    from sourceSets.main.output
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
